apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/part-of: openshift-builds
    app.kubernetes.io/version: v1.1.0
  name: openshift-builds-shared-resource-secret-configmap-share-watch-sar-create
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-builds-shared-resource-secret-configmap-share-watch-sar-create
subjects:
- kind: ServiceAccount
  name: csi-driver-shared-resource
  namespace: openshift-cluster-csi-drivers
