apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/part-of: openshift-builds
    app.kubernetes.io/version: v1.1.0
  name: openshift-builds-shared-resource-secret-configmap-share-watch-sar-create
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sharedresource.openshift.io
  resources:
  - sharedconfigmaps
  - sharedsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
